// Generated by scripts/import-audio.ts — do not edit by hand; re-run the script instead.
// Some entries (e.g. self-intro, international-job-ready) have no page yet and are intentionally unrendered.

export type AudioTrack = { title: string; src: string; peaksSrc: string; durationSec: number };
export type AudioTrackKind = "country" | "resource";

export const audioTracks: Record<AudioTrackKind, Record<string, AudioTrack>> = {
  "country": {},
  "resource": {}
};
